FROM golang:1.15-alpine

MAINTAINER ckall

ENV TZ=Asia/Shanghai

WORKDIR /var/www

COPY ./www/ /var/www

RUN echo "http://mirrors.aliyun.com/alpine/v3.4/main/" > /etc/apk/repositories \
  && apk --no-cache add tzdata zeromq \
  && ln -snf /usr/share/zoneinfo/$TZ /etc/localtime \
  && echo '$TZ' > /etc/timezone \
  && apk update \
  && apk upgrade \
  && apk add --no-cache bash git openssh \
  && go mod download \
  && go build -o main .

EXPOSE 8088

CMD ["./main"]